// Generated by CoffeeScript 1.3.3
(function() {
  var create_cancellable_notification, default_check_interval, failure, italki_checker, millis_to_persist_notifications, seconds_to_persist_notifs, sound_notif, success;

  seconds_to_persist_notifs = 60;

  millis_to_persist_notifications = seconds_to_persist_notifs * 1000;

  default_check_interval = 60 * 5 * 1000;

  sound_notif = function(what, tts) {
    if (tts == null) {
      tts = true;
    }
    if (tts) {
      return chrome.tts.speak(what);
    } else {
      return document.getElementById("audio_file").play();
    }
  };

  create_cancellable_notification = function(title, text, millis) {
    var notif;
    notif = show_notification(null, title, text);
    return setTimeout((function() {
      return notif.cancel();
    }), millis);
  };

  success = function() {
    var online_users, user, _i, _len;
    console.log("Have " + arguments.length + " users");
    online_users = [];
    for (_i = 0, _len = arguments.length; _i < _len; _i++) {
      user = arguments[_i];
      online_users.push(user);
    }
    online_users = online_users.join(",");
    create_cancellable_notification("Online users", online_users, millis_to_persist_notifications);
    return sound_notif(online_users, false);
  };

  failure = function() {
    return create_cancellable_notification("Could not resolve users", "Error resolving", millis_to_persist_notifications);
  };

  italki_checker = function() {
    return $.get("http://www.italki.com", function(data) {
      var avatar_loop, deferreds, profiles, user, _i, _len;
      avatar_loop = $("div.spacing .avater_loop li div a", data);
      console.log("Avatars: " + avatar_loop.length);
      if (avatar_loop.length > 0) {
        profiles = [];
        deferreds = [];
        for (_i = 0, _len = avatar_loop.length; _i < _len; _i++) {
          user = avatar_loop[_i];
          $.Deferred(function(dfrd) {
            $.get($(user).attr("href"), function(server_response) {
              var nick;
              nick = $("span.nickname", server_response).html();
              return dfrd.resolve(nick);
            });
            return deferreds.push(dfrd.promise());
          });
        }
        return $.when.apply(this, deferreds).then(success, failure).done(function() {
          return setTimeout(italki_checker, default_check_interval);
        });
      } else {
        create_cancellable_notification(":(", "No online users", millis_to_persist_notifications);
        return setTimeout(italki_checker, default_check_interval);
      }
    }).error(function() {
      return setTimeout(italki_checker, default_check_interval);
    });
  };

  italki_checker();

}).call(this);
